### Create a question

POST http://127.0.0.1:5000/api/questions
Content-Type: application/json

{
    "name": "Pannini Rod",
    "text": "This is a sandwich",
    "repo": "repo",
    "live": "live"
}

### View questions

GET http://127.0.0.1:5000/api/questions
Content-Type: application/json

### Edit a question


### Delete a question

DELETE http://127.0.0.1:5000/api/questions/606f5483017cbe32f4803d23
Content-Type: application/json